version : '3'

services:
    landingpage:
        image: docker.pkg.github.com/remorses/skema-playground/landingpage
        networks:
            - traefik_default
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.docker.network=traefik_default
            - "traefik.frontend.rule=Host:skema.club"
    playground:
        image: docker.pkg.github.com/remorses/skema-playground/playground
        networks:
            - traefik_default
        ports:
            - 1234:80
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.docker.network=traefik_default
            - "traefik.frontend.rule=Host:skema.club;Path:/app"
    worker:
        image: docker.pkg.github.com/remorses/skema-playground/worker
        networks:
            - traefik_default
        environment: 
            - PORT=80
        ports:
            - 8090:80
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.docker.network=traefik_default
            - "traefik.frontend.rule=Host:graphql.skema.club"

networks:
    traefik_default:
        external:
            name: traefik_default