version : '3'

services:
    landingpage:
        image: docker.pkg.github.com/remorses/skema-playground/landingpage
        labels:
            - traefik.enable=true
            - traefik.port=80
            - "traefik.frontend.rule=Host:skema.club"
    playground:
        image: docker.pkg.github.com/remorses/skema-playground/playground
        ports:
            - 1234:80
        labels:
            - traefik.enable=true
            - traefik.port=80
            - "traefik.frontend.rule=Host:skema.club;Path:/app"
    worker:
        image: docker.pkg.github.com/remorses/skema-playground/worker
        environment: 
            - PORT=80
        ports:
            - 8090:80
        labels:
            - traefik.enable=true
            - traefik.port=80
            - "traefik.frontend.rule=Host:graphql.skema.club"
