on:
    push:
        branches:
            - master
        paths:
            - 'landingpage/**'

name: landingpage
jobs:
    all:
        name: Everything
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@master
        -   name: Publish Image
            uses: remorses/github-docker@master
            with:
                username: remorses
                personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
                imageName: landingpage
                context: landingpage
        -   name: Bump Version
            uses: remorses/bump-version@js
            with:
                version_file: landingpage/VERSION
                prefix: landingpage
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


