on:
    push:
        branches:
            - master
        paths:
            - 'landingpage/**'

name: Landingpage
jobs:
    all:
        name: Everything
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@master
        -   name: Bump Version
            id: bump
            uses: remorses/bump-version@js
            with:
                version_file: landingpage/VERSION
                prefix: landingpage
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        -   run: env
            env:
                STEPS: ${{ toJson(steps) }}
                BUMP: ${{ toJson(steps.bump) }}
                OUT: ${{ toJson(steps.bump.outputs) }}
        -   name: Publish Image
            uses: remorses/github-docker@master
            with:
                username: remorses
                personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
                imageName: landingpage
                imageTag: ${{ steps.bump.outputs.version }}
                context: landingpage
                # tags: ${{ concat('latest, ', ) }}

        # -   uses: whoan/docker-build-with-cache-action@v1
        #     with:
        #         username: remorses
        #         password: "${{ secrets.GITHUB_TOKEN }}"
        #         image_name: remorses/skema-playground/playground
        #         image_tag: latest
        #         registry: docker.pkg.github.com
        #         context: playground



