on:
    push:
        branches:
            - master
        paths:
            - 'worker/**'

name: Worker
jobs:
    all:
        name: Everything
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@master
        -   name: Publish Image
            uses: remorses/github-docker@master
            with:
                username: remorses
                personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
                imageName: worker
                context: worker
        -   name: Bump Version
            uses: remorses/bump-version@js
            with:
                version_file: worker/VERSION
                prefix: worker
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


